name: Developer eXperience Doctor
title: Economics of The Developer eXperience
description: Doctor of Developer eXeprience is about economics of developer experience
tags:
  - blog
  - DX
  - API
  - Platform
  - economics
  - academic
email: jarkko@vimo.fi
disqus_username: jarkkomoilanen
show_hero: true