name: DX Doctor - Economics of The Developer eXperience
title: Doctor of Developer eXperience 
description: Doctor of Developer eXeprience is about economics of developer experience
tags:
  - blog
  - DX
  - API
  - Platform
  - economics
  - academic
email: jarkko@vimo.fi
disqus_username: jarkkomoilanen
show_hero: true